ConfigModbus:
  type: "TCP"                 # Modbus 类型（TCP/RTU）
  TCP:
    ip: "127.0.0.1"          # Modbus TCP IP 地址
    port: 502                 # Modbus TCP 端口号
  RTU:
    port_name: "/dev/ttyUSB0" # Modbus RTU 串口名称
    baudrate: 9600            # 波特率
    parity: "N"               # 校验位（无校验：N，偶校验：E，奇校验：O）
    slave_addr: 1             # 从站地址
  cmd_interval: 100           # 命令发送间隔（毫秒）
  max_retries: 3              # 最大重试次数
  retry_interval: 500         # 重试间隔（毫秒）